apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: version-manager-controller
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/kpostlet/kebechet-version-manager-controller:v0.0.0
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local