apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: version-manager-worker
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/kpostlet/keb-version-manager-worker:v0.0.1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local