apiVersion: tekton.dev/v1beta1 # TODO
kind: Pipeline
metadata:
  name: version-update-pr
  labels:
    kubernetes.io/created-by: kebechet-version-manager
spec:
  workspaces:
    name: pipeline-ws
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-ws
